{
 "title": "Service-Level Indicator",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (1 - avg_over_time(up{namespace=\"default\", service!=\"kubernetes\"}[${__range_s}s]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Backend Tracing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "operation": "homepage", "service": "backend-service" }
   ]
  },
  {
   "title": "Success requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "flask_http_request_total{namespace=\"default\", status=~\"[20]..\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "40X errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "flask_http_request_total{namespace=\"default\", status=~\"[40]..\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "50X errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total{namespace=\"default\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request duration per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (path) (flask_http_request_duration_seconds_bucket{path!~\".*static.*\"})",
     "legendFormat": "{{path}} on {{service}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}